# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Thread-Exit
version:      0.05
version_from: lib/Thread/Exit.pm
installdirs:  site
requires:
    Thread::Serialize:             0.06

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.15
